<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>HarmoniaAtlas</AssemblyName>
    <RootNamespace>HarmoniaAtlas</RootNamespace>
    <ApplicationIcon />
    <Platforms>AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lumina" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
